### PR TITLE
Routing Setup for Frontend

### LINKED ISSUE #30: setup routing

### PR DESCRIPTION
**Pull request by steffenhls**
Closes #30 
WizardStep on register page is broken

### CODE REVIEW

**Comment by lumaghg** [comment]
Ist der PR ready to merge? Es sind keine Reviews requested

**Comment by steffenhls** [comment]
> Ist der PR ready to merge? Es sind keine Reviews requested

Not ready. Problems with WizardStep Component

**Comment by lumaghg** [comment]
> > Ist der PR ready to merge? Es sind keine Reviews requested
> 
> Not ready. Problems with WizardStep Component

Please consider opening a [draft PR](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request#converting-a-pull-request-to-a-draft) instead or add the DO NOT MERGE label I just created to avoid confusion

**Comment by STAT1C-Sy** [comment]
sieht gut aus

**Review by STAT1C-Sy — APPROVED** [review]

**Pull request merged**
